---
layout: page
title: "데이터 가져오기"
subtitle: "한국 R 컨퍼런스 도서 후원"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: false
bibliography: bibliography_ingest.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 책 한권 {#get-one-book}

```{r crawl-data-book}
library(tidyverse)
library(rvest)
library(xml2)

jpub_url <- "https://jpub.tistory.com/1177"

jpub_html <- jpub_url %>% 
  read_html()

jpub_selects <- jpub_html %>% 
  html_nodes('span+ span , b')

jpub_attributes <- xml_attr(jpub_selects, "style")
jpub_values <- xml_text(jpub_selects, "style")

jpub_tbl <- tibble(key  = jpub_attributes, 
                   value = jpub_values)  %>% 
  filter(key == "color: #000000;", 
         value != "") %>% 
  select(value) %>% 
  mutate(key = c("출판사","지은이", "출판일", "페이지", "판형", "제본", "정가", "ISBN", "키워드", "분야")) %>% 
  pivot_wider(names_from = key, values_from = value)

jpub_tbl
```

