---
layout: page
title: "데이터 가져오기"
subtitle: "News API - "
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_ingest.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# NEWS API와 R 패기지 {#about-news-api}

[NEWS API](https://newsapi.org/) 에서 Key 를 받아 전세계 언론사에서 배포된 기사를 R에서 수월하게 받아 볼 수 있다. R 패키지 [`newsapi`](https://github.com/news-r/newsapi)는 R에서 바로 작업을 수월하게 할 수 있도록 도움을 준다.

# 사례 {#newsapi-example}

미리 API키를 [NEWS API](https://newsapi.org/) 웹사이트에서 발급받아 `usethis::edit_r_environ()` 명령어로 `/Users/사용자명/.Renviron` 파일에 저장을 해둔다.


```{r from-install-to-example}
library(tidyverse)
library(newsapi)

newsapi_key(Sys.getenv("NEWSAPI_KEY"))

# news_sources()

# top_headlines("Squid Game")
squid_tbl <- every_news("Squid Game")

squid_tbl %>% 
  arrange(desc(publishedAt)) %>% 
  select(source, title, content) %>% 
  reactable::reactable()

```

# 원하는 뉴스만 {#all-we-want}

## 언론사 {#journal-company}

```{r customization}
news_sources() %>% 
  reactable::reactable()
```

## 헤드라인 {#headline}

```{r headline}
# top_headlines("lee jae-myung")
top_headlines("Korea") %>% 
  select(source, title, content) %>% 
  reactable::reactable()
```


## 시점 {#timeline}

```{r headline-timeline}
korea_tbl <- every_news("Korea", since = "2021-10-01", until = "2021-10-31")
korea_tbl %>% 
  select(source, title, content, publishedAt) %>% 
  reactable::reactable()

```

