---
layout: page
title: "검정배경 흰색글자 인식"
author:
  - name: Tidyverse Korea
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```


# OCR 대상 이미지 [^ocr-images] {#ocr-image}

[^ocr-images]: [stackoverflow, "tesseract in R - read white font on black background"](https://stackoverflow.com/questions/59750745/tesseract-in-r-read-white-font-on-black-background)

검은색 배경에 흰색글씨가 담긴 이미지에서 텍스트를 추출하는 사례를 살펴보자. 스택오버플로우 ["tesseract in R - read white font on black background"](https://stackoverflow.com/questions/59750745/tesseract-in-r-read-white-font-on-black-background)에 올라온 한장의 이미지를 가지고 시작해보자.

```{r ocr-image}
library(tidyverse)
library(magick)
library(tesseract)

char_image <- image_read("fig/white-character.jpeg")

char_image %>% 
  image_resize("2000x")

```

## 이미지 전처리 {#preprocess-images}

`magick` 객체보다 숫자로 작업하는 것이 경우에 따라서는 더 수월한 경우도 많다.

```{r preprocess-images}

input <- char_image %>% 
  .[[1]] %>% 
  as.numeric() # 숫자가 작업하기 수월하다.

image_read(ifelse(input < .9, 1, 0) ) 
```

## 텍스트 추출 {#extract-ocr-text}

```{r extract-text-from-image}
ifelse(input < .9, 1, 0) %>% 
  image_read() %>% 
  image_resize('500x') %>% # make it smaller to work around the errors
  tesseract::ocr( engine = "eng")
```

