---
layout: page
title: "광학문자인식(OCR, Optical Character Recognition)"
subtitle: "애비(Abbyy): Access Abbyy Cloud OCR from R"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```


# 애비 클라우드 {#abbyy-cloud}

1. [ABBYY Cloud OCR SDK](https://www.ocrsdk.com/)에 접속하여 계정을 생성한다.
1. 가입이 완료되면 `Application ID`와 비번을 등록한 전자우편을 통해 확인할 수 있다.

# `abbyyR` 설치 {#install-abbyyR}

```{r install-abbyyR, error=TRUE}
# devtools::install_github("soodoku/abbyyR", build_vignettes = TRUE)
library(abbyyR)
setapp(c(Sys.getenv("ABBYY_ID"), Sys.getenv("ABBYY_PW")))

getAppInfo()




```

